kmq:
    client:
        serverAddress: localhost
        port: 8080
        queueLimits:
            "topic": 1
        queues:
            - "topic"

spring:
    main:
        web-application-type: none